{
  "events": [
    {
      "name": "WiDS@UBC x USS DataVerse Datathon",
      "organizer": "WiDS@UBC & USS",
      "date": "2025-11-22T09:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-11-15",
      "price": "Free",
      "type": "Datathon",
      "category": ["AI", "Data Science", "Statistics"],
      "faculty": ["Science", "BUCS", "Computer Science"],
      "link": "https://ubc.ca1.qualtrics.com/jfe/form/SV_2gaOyAyImjHTcdE",
      "location": "UBC LIFE Building, Room 2302",
      "image": "https://example.com/wids_datathon.jpg"
    },
    {
      "name": "WiCS Vibe-Code-a-Thon",
      "organizer": "UBC WiCS",
      "date": "2025-11-26T17:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-11-20",
      "price": "Free",
      "type": "Hackathon",
      "category": ["AI", "Web", "Software"],
      "faculty": ["Computer Science", "Engineering"],
      "link": "https://ubc.ca1.qualtrics.com/jfe/form/SV_0fiYpLudPTEsiSW",
      "location": "Hugh Dempster Pavilion (DMP 301)",
      "image": "https://example.com/wics_vibehack.jpg"
    },
    {
      "name": "UBC CIC Fall 2025 GenAI Hackathon",
      "organizer": "UBC Cloud Innovation Centre",
      "date": "2025-11-12T09:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-11-02",
      "price": "Free",
      "type": "Hackathon",
      "category": ["AI", "Cloud", "GenAI"],
      "faculty": ["Engineering", "Computer Science"],
      "link": "https://cic.ubc.ca/ubc-cic-fall-2025-genai-hackathon/",
      "location": "UBC CIC / Cloud Innovation Centre",
      "image": "https://example.com/cic_genai.jpg"
    },
    {
      "name": "Science Case Competition 2025",
      "organizer": "SCI Team / UBC Science",
      "date": "2025-11-05T17:30:00",
      "difficulty": "Hard",
      "applicationDeadline": "2025-10-24",
      "price": "Free",
      "type": "Case Competition",
      "category": ["Science", "Strategy", "Research"],
      "faculty": ["Science"],
      "link": "https://science.ubc.ca/students/events/science-case-competition",
      "location": "UBC Science Building",
      "image": "https://example.com/science_case.jpg"
    },
    {
      "name": "UBC Technical Career Fair (TCF)",
      "organizer": "UBC CSSS",
      "date": "2025-01-22T08:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-01-15",
      "price": "Free",
      "type": "Career Fair",
      "category": ["Networking", "Career", "Industry"],
      "faculty": ["Computer Science", "Engineering", "BUCS"],
      "link": "https://ubccsss.org/tcf/",
      "location": "UBC Alumni Centre, Jack Poole Hall",
      "image": "https://example.com/tcf_2025.jpg"
    },
    {
      "name": "UBC Medicine Datathon 2025",
      "organizer": "UBC DASH / Data Science & Health",
      "date": "2025-03-22T09:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-03-10",
      "price": "Free",
      "type": "Datathon",
      "category": ["Health", "AI", "Data Science"],
      "faculty": ["Medicine", "Computer Science", "Public Health"],
      "link": "https://datascienceandhealth.ubc.ca/events/ubc-medicine-datathon",
      "location": "Life Sciences Centre, UBC",
      "image": "https://example.com/med_datathon.jpg"
    },
    {
      "name": "youCode @ UBC Hackathon",
      "organizer": "WiDS@UBC & WiCS",
      "date": "2025-04-05T12:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-03-31",
      "price": "Free",
      "type": "Hackathon",
      "category": ["Diversity", "Web", "Tech for Good"],
      "faculty": ["Computer Science", "Engineering", "Arts"],
      "link": "https://ubcyoucode.com/",
      "location": "UBC Campus",
      "image": "https://example.com/youcode_ubc.jpg"
    },
    {
      "name": "Innovation UBC Immersion Week Showcase",
      "organizer": "Innovation UBC",
      "date": "2025-09-23T08:30:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-09-01",
      "price": "Free",
      "type": "Conference / Showcase",
      "category": ["Entrepreneurship", "Innovation", "Startup"],
      "faculty": ["All"],
      "link": "https://innovation.ubc.ca/impact-updates/events/agenda",
      "location": "Robson Square, Vancouver",
      "image": "https://example.com/immersion_week.jpg"
    },
    {
      "name": "iGEM UBC Team Info Session",
      "organizer": "iGEM UBC",
      "date": "2025-10-10T18:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-10-09",
      "price": "Free",
      "type": "Info Session",
      "category": ["Biology", "Engineering", "Synthetic Biology"],
      "faculty": ["Science", "Engineering"],
      "link": "https://igem.ubc.ca/join",
      "location": "Henry Angus Building",
      "image": "https://example.com/igem_info.jpg"
    },
    {
      "name": "UBC Business Case Workshop",
      "organizer": "Sauder Summit",
      "date": "2025-11-15T17:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-11-10",
      "price": "Free",
      "type": "Workshop",
      "category": ["Business", "Case Competition"],
      "faculty": ["Sauder"],
      "link": "https://www.saudersummit.ca/events",
      "location": "Sauder Learning Labs",
      "image": "https://example.com/sauder_case_workshop.jpg"
    },
    {
      "name": "Sustainability Innovation Hack",
      "organizer": "UBC Sustainability Club",
      "date": "2025-12-05T10:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-11-25",
      "price": "Free",
      "type": "Hackathon",
      "category": ["Sustainability", "Environment", "Design"],
      "faculty": ["Land & Food Systems", "Engineering", "Science"],
      "link": "https://ubcsustainability.ca/events/hack",
      "location": "AMS Nest, UBC",
      "image": "https://example.com/sustain_hack.jpg"
    },
    {
      "name": "Peer Tutoring Workshop Night",
      "organizer": "UBC Tutoring Services",
      "date": "2025-10-20T18:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-10-18",
      "price": "Free",
      "type": "Workshop",
      "category": ["Education", "Study Skills"],
      "faculty": ["All"],
      "link": "https://students.ubc.ca/academics/tutoring",
      "location": "Koerner Library",
      "image": "https://example.com/tutoring_workshop.jpg"
    },
    {
      "name": "Robotics Design Competition",
      "organizer": "UBC Engineering Design Team",
      "date": "2025-11-30T09:00:00",
      "difficulty": "Hard",
      "applicationDeadline": "2025-11-10",
      "price": "$20",
      "type": "Competition",
      "category": ["Robotics", "Engineering", "Hardware"],
      "faculty": ["Engineering"],
      "link": "https://ubcengdesign.com/competition",
      "location": "Joe Enns Building",
      "image": "https://example.com/robotics_comp.jpg"
    },
    {
      "name": "Sociology Research Networking Night",
      "organizer": "UBC Sociology Dept",
      "date": "2025-10-25T17:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-10-20",
      "price": "Free",
      "type": "Networking",
      "category": ["Social Science", "Research"],
      "faculty": ["Arts", "Social Sciences"],
      "link": "https://socdev.sociology.ubc.ca/events/network-night",
      "location": "Allard Hall",
      "image": "https://example.com/soc_net.jpg"
    },
    {
      "name": "Finance Case Competition",
      "organizer": "UBC Finance Association",
      "date": "2025-12-12T13:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-12-01",
      "price": "$5",
      "type": "Case Competition",
      "category": ["Finance", "Business"],
      "faculty": ["Sauder", "BUCS"],
      "link": "https://ubcfa.com/events/case",
      "location": "Henry Angus Building",
      "image": "https://example.com/finance_case.jpg"
    },
    {
      "name": "AI Ethics Lecture Series",
      "organizer": "UBC Ethics & Technology Group",
      "date": "2025-11-16T16:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-11-10",
      "price": "Free",
      "type": "Talk",
      "category": ["AI", "Ethics", "Philosophy"],
      "faculty": ["Arts", "Computer Science"],
      "link": "https://innovation.ubc.ca/events/ai-ethics",
      "location": "ICICS Building",
      "image": "https://example.com/ai_ethics.jpg"
    },
    {
      "name": "Biomedical Data Science Workshop",
      "organizer": "UBC Biomedical Engineering",
      "date": "2025-10-18T13:00:00",
      "difficulty": "Hard",
      "applicationDeadline": "2025-10-10",
      "price": "Free",
      "type": "Workshop",
      "category": ["Data Science", "Bioengineering"],
      "faculty": ["Engineering", "Science", "Medicine"],
      "link": "https://bme.ubc.ca/events/data-workshop",
      "location": "Biomedical Engineering Lab",
      "image": "https://example.com/bme_data.jpg"
    },
    {
      "name": "First-Year Leadership Retreat",
      "organizer": "UBC AMS",
      "date": "2025-09-12T09:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-08-30",
      "price": "Free",
      "type": "Retreat",
      "category": ["Leadership", "Community"],
      "faculty": ["All"],
      "link": "https://ams.ubc.ca/events/leadership-retreat",
      "location": "UBC Camps & Retreat Centre",
      "image": "https://example.com/leadership_retreat.jpg"
    },
    {
      "name": "Blockchain & Cryptocurrency Panel",
      "organizer": "Sauder Blockchain Club",
      "date": "2025-11-20T18:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-11-18",
      "price": "Free",
      "type": "Panel",
      "category": ["Blockchain", "Finance", "Crypto"],
      "faculty": ["Sauder", "Computer Science", "Engineering"],
      "link": "https://sauderblockchain.ubc.ca/events",
      "location": "Henry Angus Building",
      "image": "https://example.com/blockchain_panel.jpg"
    },
    {
      "name": "Sustainability Case Competition",
      "organizer": "Land & Food Systems Student Society",
      "date": "2025-11-28T10:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-11-15",
      "price": "Free",
      "type": "Case Competition",
      "category": ["Sustainability", "Business", "Policy"],
      "faculty": ["Land & Food Systems", "Arts"],
      "link": "https://lfsss.ubc.ca/events/casecomp",
      "location": "Allard Hall",
      "image": "https://example.com/sustain_case.jpg"
    },
    {
      "name": "Quantum Computing Seminar",
      "organizer": "UBC Physics Club",
      "date": "2025-12-08T14:00:00",
      "difficulty": "Hard",
      "applicationDeadline": "2025-12-01",
      "price": "Free",
      "type": "Seminar",
      "category": ["Physics", "Quantum", "Computer Science"],
      "faculty": ["Science", "Engineering"],
      "link": "https://physics.ubc.ca/events/quantum-seminar",
      "location": "Hennings Physics Building",
      "image": "https://example.com/quantum_seminar.jpg"
    },
    {
      "name": "Spanish Language & Culture Mixer",
      "organizer": "UBC Modern Languages Society",
      "date": "2025-10-30T17:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-10-28",
      "price": "Free",
      "type": "Social / Networking",
      "category": ["Language", "Arts", "Culture"],
      "faculty": ["Arts"],
      "link": "https://mls.ubc.ca/events/spanish-mixer",
      "location": "AMS Nest Lounge",
      "image": "https://example.com/spanish_mixer.jpg"
    },
    {
      "name": "Data Science Career Panel",
      "organizer": "UBC Statistics Club",
      "date": "2025-11-18T18:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-11-15",
      "price": "Free",
      "type": "Panel",
      "category": ["Data Science", "Industry", "AI"],
      "faculty": ["Science", "BUCS", "Computer Science"],
      "link": "https://stat.ubc.ca/events/career-panel",
      "location": "Henry Angus Building",
      "image": "https://example.com/data_career_panel.jpg"
    },
    {
      "name": "Sustainability Film Screening",
      "organizer": "UBC Environmental Club",
      "date": "2025-10-22T19:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-10-20",
      "price": "Free",
      "type": "Social",
      "category": ["Environment", "Sustainability", "Film"],
      "faculty": ["Land & Food Systems", "Science", "Arts"],
      "link": "https://env.ubc.ca/events/film-night",
      "location": "AMS Nest Theatre",
      "image": "https://example.com/sustain_film.jpg"
    },
    {
      "name": "Undergraduate Research Info Session",
      "organizer": "UBC Office of Research",
      "date": "2025-09-25T17:30:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-09-20",
      "price": "Free",
      "type": "Info Session",
      "category": ["Research", "Science", "Engineering"],
      "faculty": ["Science", "Engineering"],
      "link": "https://research.ubc.ca/events/undergrad-info",
      "location": "Chemistry Building, UBC",
      "image": "https://example.com/research_info.jpg"
    },
    {
      "name": "Design Thinking Bootcamp",
      "organizer": "UBC Design Club",
      "date": "2025-11-01T10:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-10-25",
      "price": "$10",
      "type": "Workshop",
      "category": ["Design", "Product", "Innovation"],
      "faculty": ["Engineering", "Arts", "Business"],
      "link": "https://ubcdesign.club/events/bootcamp",
      "location": "AMS Nest",
      "image": "https://example.com/design_bootcamp.jpg"
    },
    {
      "name": "Quantum Algorithms Hack",
      "organizer": "UBC Quantum Club",
      "date": "2025-12-15T09:00:00",
      "difficulty": "Hard",
      "applicationDeadline": "2025-12-01",
      "price": "Free",
      "type": "Hackathon",
      "category": ["Quantum", "Algorithms", "Physics"],
      "faculty": ["Engineering", "Science"],
      "link": "https://ubcquantum.com/events/quantum-hack",
      "location": "Hennings Physics Building, UBC",
      "image": "https://example.com/quantum_hack.jpg"
    },
    {
      "name": "Public Health Data Jam",
      "organizer": "UBC PHSA / Public Health Club",
      "date": "2025-11-14T10:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-11-05",
      "price": "Free",
      "type": "Data Jam",
      "category": ["Public Health", "Data Science", "Policy"],
      "faculty": ["Public Health", "Science", "Arts"],
      "link": "https://ph.ubc.ca/events/data-jam",
      "location": "Life Sciences Centre",
      "image": "https://example.com/ph_datajam.jpg"
    },
    {
      "name": "Entrepreneurship Bootcamp",
      "organizer": "Sauder Entrepreneurship Club",
      "date": "2025-10-12T09:00:00",
      "difficulty": "Easy",
      "applicationDeadline": "2025-10-04",
      "price": "$20",
      "type": "Bootcamp",
      "category": ["Business", "Startup", "Entrepreneurship"],
      "faculty": ["Sauder", "BUCS", "Engineering"],
      "link": "https://sauderclub.ubc.ca/entrepreneurship-bootcamp",
      "location": "Sauder Learning Labs",
      "image": "https://example.com/ent_bootcamp.jpg"
    },
    {
      "name": "Machine Learning Study Group",
      "organizer": "UBC ML Club",
      "date": "2025-10-07T18:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-10-06",
      "price": "Free",
      "type": "Meetup",
      "category": ["AI", "Machine Learning"],
      "faculty": ["Computer Science", "Engineering", "Science"],
      "link": "https://ml.ubc.ca/events/study-group",
      "location": "ICICS X350",
      "image": "https://example.com/ml_study.jpg"
    },
    {
      "name": "Nonprofit Case Competition",
      "organizer": "UBC Social Impact Club",
      "date": "2025-11-18T10:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-11-05",
      "price": "$5",
      "type": "Case Competition",
      "category": ["Social Impact", "Business", "Nonprofit"],
      "faculty": ["Arts", "Sauder", "BUCS"],
      "link": "https://ubcsocialimpact.ca/events/casecomp",
      "location": "AMS Nest",
      "image": "https://example.com/social_case.jpg"
    },
    {
      "name": "Cybersecurity Capture-the-Flag Workshop",
      "organizer": "UBC Competitive Programming Club",
      "date": "2025-12-03T13:00:00",
      "difficulty": "Hard",
      "applicationDeadline": "2025-12-01",
      "price": "Free",
      "type": "Workshop / Competition",
      "category": ["Security", "CS", "Algorithms"],
      "faculty": ["Computer Science", "Engineering"],
      "link": "https://icpc.cs.ubc.ca/ctf-workshop",
      "location": "ICICS Building",
      "image": "https://example.com/ctf_workshop.jpg"
    },
    {
      "name": "UBC Data & Ethics Hackathon",
      "organizer": "UBC Ethics & Data Club",
      "date": "2025-11-08T10:00:00",
      "difficulty": "Medium",
      "applicationDeadline": "2025-11-01",
      "price": "$10",
      "type": "Hackathon",
      "category": ["Data Science", "Ethics"],
      "faculty": ["All"],
      "link": "https://ethicsanddata.ubc.ca/events/hackathon",
      "location": "AMS Nest",
      "image": "https://example.com/data_ethics.jpg"
    }
  ]
}
